### ISSUE TITLE
Trying pwnbox with podman instead of docker and getting this error

### ISSUE THREAD

**Issue by testn** [DeadPackets/pwnbox#11]
```Traceback (most recent call last):
  File "/opt/homebrew/bin/pwnbox", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/pwnbox/__main__.py", line 218, in main
    registry_data = client.images.get_registry_data(
  File "/opt/homebrew/lib/python3.10/site-packages/docker/models/images.py", line 335, in get_registry_data
    attrs=self.client.api.inspect_distribution(name, auth_config),
  File "/opt/homebrew/lib/python3.10/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/docker/api/image.py", line 287, in inspect_distribution
    return self._result(
  File "/opt/homebrew/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/opt/homebrew/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/homebrew/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.40/distribution/registry.hub.docker.com/deadpackets/pwnbox:latest/json: Not Found ("b'Not Found'")```

**Comment by DeadPackets** [comment]
This seems to be an issue with some local docker repository you got running? It's trying to pull the image from that local container image registry.
